In [54]:
##Importing all the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore') # because of version mismatch, if there are any warnings, it will be ignored

In [59]:
## Reading the loan dataset as csv
loan_data=pd.read_csv('loan1.csv')

#printing columns of the dataset
#print(loan_data.columns)

#printing the first 5 records
print(loan_data.head())


##[39717 rows x 111 columns]

   id       member_id  loan_amnt  funded_amnt  funded_amnt_inv  ... tax_liens tot_hi_cred_lim  total_bal_ex_mort total_bc_limit total_il_high_credit_limit
0  1077501  1296599     5000       5000         4975.0          ...  0.0      NaN             NaN                NaN            NaN
1  1077430  1314167     2500       2500         2500.0          ...  0.0      NaN             NaN                NaN            NaN
2  1077175  1313524     2400       2400         2400.0          ...  0.0      NaN             NaN                NaN            NaN
3  1076863  1277178    10000      10000        10000.0          ...  0.0      NaN             NaN                NaN            NaN
4  1075358  1311748     3000       3000         3000.0          ...  0.0      NaN             NaN                NaN            NaN

[5 rows x 111 columns]

In [66]:
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns',111) ##Since we have 111 columns in total initially
pd.set_option('display.width', 1000)
pd.set_option('display.colheader_justify', 'left')
#pd.set_option('display.precision', 2)

In [67]:
loan_data.dtypes

id                                  int64
member_id                           int64
loan_amnt                           int64
funded_amnt                         int64
funded_amnt_inv                   float64
term                               object
int_rate                           object
installment                       float64
grade                              object
sub_grade                          object
emp_title                          object
emp_length                         object
home_ownership                     object
annual_inc                        float64
verification_status                object
issue_d                            object
loan_status                        object
pymnt_plan                         object
url                                object
desc                               object
purpose                            object
title                              object
zip_code                           object
addr_state                         object
dti                               float64
delinq_2yrs                         int64
earliest_cr_line                   object
inq_last_6mths                      int64
mths_since_last_delinq            float64
mths_since_last_record            float64
open_acc                            int64
pub_rec                             int64
revol_bal                           int64
revol_util                         object
total_acc                           int64
initial_list_status                object
out_prncp                         float64
out_prncp_inv                     float64
total_pymnt                       float64
total_pymnt_inv                   float64
total_rec_prncp                   float64
total_rec_int                     float64
total_rec_late_fee                float64
recoveries                        float64
collection_recovery_fee           float64
last_pymnt_d                       object
last_pymnt_amnt                   float64
next_pymnt_d                       object
last_credit_pull_d                 object
collections_12_mths_ex_med        float64
mths_since_last_major_derog       float64
policy_code                         int64
application_type                   object
annual_inc_joint                  float64
dti_joint                         float64
verification_status_joint         float64
acc_now_delinq                      int64
tot_coll_amt                      float64
tot_cur_bal                       float64
open_acc_6m                       float64
open_il_6m                        float64
open_il_12m                       float64
open_il_24m                       float64
mths_since_rcnt_il                float64
total_bal_il                      float64
il_util                           float64
open_rv_12m                       float64
open_rv_24m                       float64
max_bal_bc                        float64
all_util                          float64
total_rev_hi_lim                  float64
inq_fi                            float64
total_cu_tl                       float64
inq_last_12m                      float64
acc_open_past_24mths              float64
avg_cur_bal                       float64
bc_open_to_buy                    float64
bc_util                           float64
chargeoff_within_12_mths          float64
delinq_amnt                         int64
mo_sin_old_il_acct                float64
mo_sin_old_rev_tl_op              float64
mo_sin_rcnt_rev_tl_op             float64
mo_sin_rcnt_tl                    float64
mort_acc                          float64
mths_since_recent_bc              float64
mths_since_recent_bc_dlq          float64
mths_since_recent_inq             float64
mths_since_recent_revol_delinq    float64
num_accts_ever_120_pd             float64
num_actv_bc_tl                    float64
num_actv_rev_tl                   float64
num_bc_sats                       float64
num_bc_tl                         float64
num_il_tl                         float64
num_op_rev_tl                     float64
num_rev_accts                     float64
num_rev_tl_bal_gt_0               float64
num_sats                          float64
num_tl_120dpd_2m                  float64
num_tl_30dpd                      float64
num_tl_90g_dpd_24m                float64
num_tl_op_past_12m                float64
pct_tl_nvr_dlq                    float64
percent_bc_gt_75                  float64
pub_rec_bankruptcies              float64
tax_liens                         float64
tot_hi_cred_lim                   float64
total_bal_ex_mort                 float64
total_bc_limit                    float64
total_il_high_credit_limit        float64
dtype: object

In [68]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: float64(74), int64(13), object(24)
memory usage: 33.6+ MB

In [69]:
loan_data.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,3.97e+04,3.97e+04,39717.00,39717.00,39717.00,39717.00,3.97e+04,39717.00,39717.00,39717.00,14035.00,2786.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39717.00,39661.0,0.0,39717.0,0.0,0.0,0.0,39717.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39661.0,39717.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39020.00,39678.0,0.0,0.0,0.0,0.0
mean,6.83e+05,8.50e+05,11219.44,10947.71,10397.45,324.56,6.90e+04,13.32,0.15,0.87,35.90,69.70,9.29,0.06,13382.53,22.09,51.23,50.99,12153.60,11567.15,9793.35,2263.66,1.36,95.22,12.41,2678.83,0.0,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.04,0.0,NaN,NaN,NaN,NaN
std,2.11e+05,2.66e+05,7456.67,7187.24,7128.45,208.87,6.38e+04,6.68,0.49,1.07,22.02,43.82,4.40,0.24,15885.02,11.40,375.17,373.82,9042.04,8942.67,7065.52,2608.11,7.29,688.74,148.67,4447.14,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.20,0.0,NaN,NaN,NaN,NaN
min,5.47e+04,7.07e+04,500.00,500.00,0.00,15.69,4.00e+03,0.00,0.00,0.00,0.00,0.00,2.00,0.00,0.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN
25%,5.16e+05,6.67e+05,5500.00,5400.00,5000.00,167.02,4.04e+04,8.17,0.00,0.00,18.00,22.00,6.00,0.00,3703.00,13.00,0.00,0.00,5576.93,5112.31,4600.00,662.18,0.00,0.00,0.00,218.68,0.0,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN
50%,6.66e+05,8.51e+05,10000.00,9600.00,8975.00,280.22,5.90e+04,13.40,0.00,1.00,34.00,90.00,9.00,0.00,8850.00,20.00,0.00,0.00,9899.64,9287.15,8000.00,1348.91,0.00,0.00,0.00,546.14,0.0,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN
75%,8.38e+05,1.05e+06,15000.00,15000.00,14400.00,430.78,8.23e+04,18.60,0.00,1.00,52.00,104.00,12.00,0.00,17058.00,29.00,0.00,0.00,16534.43,15798.81,13653.26,2833.40,0.00,0.00,0.00,3293.16,0.0,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN
max,1.08e+06,1.31e+06,35000.00,35000.00,35000.00,1305.19,6.00e+06,29.99,11.00,8.00,120.00,129.00,44.00,4.00,149588.00,90.00,6311.47,6307.37,58563.68,58563.68,35000.02,23563.68,180.20,29623.35,7002.19,36115.20,0.0,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.0,NaN,NaN,NaN,NaN

In [71]:
Cols_having_nulls=loan_data.isnull().sum()
print(type(Cols_having_nulls))
print(Cols_having_nulls)

<class 'pandas.core.series.Series'>
id                                    0
member_id                             0
loan_amnt                             0
funded_amnt                           0
funded_amnt_inv                       0
term                                  0
int_rate                              0
installment                           0
grade                                 0
sub_grade                             0
emp_title                          2459
emp_length                         1075
home_ownership                        0
annual_inc                            0
verification_status                   0
issue_d                               0
loan_status                           0
pymnt_plan                            0
url                                   0
desc                              12940
purpose                               0
title                                11
zip_code                              0
addr_state                            0
dti                                   0
delinq_2yrs                           0
earliest_cr_line                      0
inq_last_6mths                        0
mths_since_last_delinq            25682
mths_since_last_record            36931
open_acc                              0
pub_rec                               0
revol_bal                             0
revol_util                           50
total_acc                             0
initial_list_status                   0
out_prncp                             0
out_prncp_inv                         0
total_pymnt                           0
total_pymnt_inv                       0
total_rec_prncp                       0
total_rec_int                         0
total_rec_late_fee                    0
recoveries                            0
collection_recovery_fee               0
last_pymnt_d                         71
last_pymnt_amnt                       0
next_pymnt_d                      38577
last_credit_pull_d                    2
collections_12_mths_ex_med           56
mths_since_last_major_derog       39717
policy_code                           0
application_type                      0
annual_inc_joint                  39717
dti_joint                         39717
verification_status_joint         39717
acc_now_delinq                        0
tot_coll_amt                      39717
tot_cur_bal                       39717
open_acc_6m                       39717
open_il_6m                        39717
open_il_12m                       39717
open_il_24m                       39717
mths_since_rcnt_il                39717
total_bal_il                      39717
il_util                           39717
open_rv_12m                       39717
open_rv_24m                       39717
max_bal_bc                        39717
all_util                          39717
total_rev_hi_lim                  39717
inq_fi                            39717
total_cu_tl                       39717
inq_last_12m                      39717
acc_open_past_24mths              39717
avg_cur_bal                       39717
bc_open_to_buy                    39717
bc_util                           39717
chargeoff_within_12_mths             56
delinq_amnt                           0
mo_sin_old_il_acct                39717
mo_sin_old_rev_tl_op              39717
mo_sin_rcnt_rev_tl_op             39717
mo_sin_rcnt_tl                    39717
mort_acc                          39717
mths_since_recent_bc              39717
mths_since_recent_bc_dlq          39717
mths_since_recent_inq             39717
mths_since_recent_revol_delinq    39717
num_accts_ever_120_pd             39717
num_actv_bc_tl                    39717
num_actv_rev_tl                   39717
num_bc_sats                       39717
num_bc_tl                         39717
num_il_tl                         39717
num_op_rev_tl                     39717
num_rev_accts                     39717
num_rev_tl_bal_gt_0               39717
num_sats                          39717
num_tl_120dpd_2m                  39717
num_tl_30dpd                      39717
num_tl_90g_dpd_24m                39717
num_tl_op_past_12m                39717
pct_tl_nvr_dlq                    39717
percent_bc_gt_75                  39717
pub_rec_bankruptcies                697
tax_liens                            39
tot_hi_cred_lim                   39717
total_bal_ex_mort                 39717
total_bc_limit                    39717
total_il_high_credit_limit        39717
dtype: int64

In [72]:
Cols_having_nan=loan_data.isna().sum() ##Nan - not an integer, indicating missing values, 
#There are around columns having all records as Nans, those columns do not contribute much for the analysis, hence we can drop them

print(type(Cols_having_nan))
print(Cols_having_nan)

<class 'pandas.core.series.Series'>
id                                    0
member_id                             0
loan_amnt                             0
funded_amnt                           0
funded_amnt_inv                       0
term                                  0
int_rate                              0
installment                           0
grade                                 0
sub_grade                             0
emp_title                          2459
emp_length                         1075
home_ownership                        0
annual_inc                            0
verification_status                   0
issue_d                               0
loan_status                           0
pymnt_plan                            0
url                                   0
desc                              12940
purpose                               0
title                                11
zip_code                              0
addr_state                            0
dti                                   0
delinq_2yrs                           0
earliest_cr_line                      0
inq_last_6mths                        0
mths_since_last_delinq            25682
mths_since_last_record            36931
open_acc                              0
pub_rec                               0
revol_bal                             0
revol_util                           50
total_acc                             0
initial_list_status                   0
out_prncp                             0
out_prncp_inv                         0
total_pymnt                           0
total_pymnt_inv                       0
total_rec_prncp                       0
total_rec_int                         0
total_rec_late_fee                    0
recoveries                            0
collection_recovery_fee               0
last_pymnt_d                         71
last_pymnt_amnt                       0
next_pymnt_d                      38577
last_credit_pull_d                    2
collections_12_mths_ex_med           56
mths_since_last_major_derog       39717
policy_code                           0
application_type                      0
annual_inc_joint                  39717
dti_joint                         39717
verification_status_joint         39717
acc_now_delinq                        0
tot_coll_amt                      39717
tot_cur_bal                       39717
open_acc_6m                       39717
open_il_6m                        39717
open_il_12m                       39717
open_il_24m                       39717
mths_since_rcnt_il                39717
total_bal_il                      39717
il_util                           39717
open_rv_12m                       39717
open_rv_24m                       39717
max_bal_bc                        39717
all_util                          39717
total_rev_hi_lim                  39717
inq_fi                            39717
total_cu_tl                       39717
inq_last_12m                      39717
acc_open_past_24mths              39717
avg_cur_bal                       39717
bc_open_to_buy                    39717
bc_util                           39717
chargeoff_within_12_mths             56
delinq_amnt                           0
mo_sin_old_il_acct                39717
mo_sin_old_rev_tl_op              39717
mo_sin_rcnt_rev_tl_op             39717
mo_sin_rcnt_tl                    39717
mort_acc                          39717
mths_since_recent_bc              39717
mths_since_recent_bc_dlq          39717
mths_since_recent_inq             39717
mths_since_recent_revol_delinq    39717
num_accts_ever_120_pd             39717
num_actv_bc_tl                    39717
num_actv_rev_tl                   39717
num_bc_sats                       39717
num_bc_tl                         39717
num_il_tl                         39717
num_op_rev_tl                     39717
num_rev_accts                     39717
num_rev_tl_bal_gt_0               39717
num_sats                          39717
num_tl_120dpd_2m                  39717
num_tl_30dpd                      39717
num_tl_90g_dpd_24m                39717
num_tl_op_past_12m                39717
pct_tl_nvr_dlq                    39717
percent_bc_gt_75                  39717
pub_rec_bankruptcies                697
tax_liens                            39
tot_hi_cred_lim                   39717
total_bal_ex_mort                 39717
total_bc_limit                    39717
total_il_high_credit_limit        39717
dtype: int64

In [81]:
##Getting list of columns where all records are null

print(loan_data.columns[loan_data.isnull().all(0)].size) ##54 columns are totally nulls and there is no use in our analysis
print(loan_data.columns[loan_data.isnull().all(0)])

54
Index(['mths_since_last_major_derog', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit'],
      dtype='object')

In [82]:
loan_data.agg(['count', 'size', 'nunique'])

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,37258,38642,39717,39717,39717,39717,39717,39717,39717,26777,39717,39706,39717,39717,39717,39717,39717,39717,14035,2786,39717,39717,39717,39667,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39646,39717,1140,39715,39661,0,39717,39717,0,0,0,39717,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,39661,39717,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,39020,39678,0,0,0,0
size,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717,39717
nunique,39717,39717,885,1041,8205,2,371,15383,7,35,28820,11,5,5318,3,55,3,1,39717,26527,14,19615,823,50,2868,11,526,9,95,111,40,5,21711,1089,82,1,1137,1138,37850,37518,7976,35148,1356,4040,2616,101,34930,2,106,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,1,0,0,0,0

In [83]:
loan_data1=loan_data.dropna(axis=1,how='all')
loan_data1.shape

(39717, 57)

In [86]:
loan_data1.isnull().all(axis=1).count()

39717

In [87]:
# function to get the percentage of null values
def get_null_value(loan_data1):
    op=round(loan_data1.isnull().sum()/len(loan_data1)*100, 2)
    return op

In [94]:
Cols_nulls=get_null_value(loan_data1) 
Cols_nulls
##There are few columns where there are 100% null values and columns where more than 50% of the values are null, hence removing them as well

id                             0.00
member_id                      0.00
loan_amnt                      0.00
funded_amnt                    0.00
funded_amnt_inv                0.00
term                           0.00
int_rate                       0.00
installment                    0.00
grade                          0.00
sub_grade                      0.00
emp_title                      6.19
emp_length                     2.71
home_ownership                 0.00
annual_inc                     0.00
verification_status            0.00
issue_d                        0.00
loan_status                    0.00
pymnt_plan                     0.00
url                            0.00
desc                          32.58
purpose                        0.00
title                          0.03
zip_code                       0.00
addr_state                     0.00
dti                            0.00
delinq_2yrs                    0.00
earliest_cr_line               0.00
inq_last_6mths                 0.00
mths_since_last_delinq        64.66
mths_since_last_record        92.99
open_acc                       0.00
pub_rec                        0.00
revol_bal                      0.00
revol_util                     0.13
total_acc                      0.00
initial_list_status            0.00
out_prncp                      0.00
out_prncp_inv                  0.00
total_pymnt                    0.00
total_pymnt_inv                0.00
total_rec_prncp                0.00
total_rec_int                  0.00
total_rec_late_fee             0.00
recoveries                     0.00
collection_recovery_fee        0.00
last_pymnt_d                   0.18
last_pymnt_amnt                0.00
next_pymnt_d                  97.13
last_credit_pull_d             0.01
collections_12_mths_ex_med     0.14
policy_code                    0.00
application_type               0.00
acc_now_delinq                 0.00
chargeoff_within_12_mths       0.14
delinq_amnt                    0.00
pub_rec_bankruptcies           1.75
tax_liens                      0.10
dtype: float64

In [96]:
##Removing columns where there is >50% of nulls as they are not useful in data analysis.
Cols_nulls_50=Cols_nulls[Cols_nulls>50]
print(Cols_nulls_50)
print(len(Cols_nulls_50.index))

mths_since_last_delinq    64.66
mths_since_last_record    92.99
next_pymnt_d              97.13
dtype: float64
3

In [97]:
loan_data1.drop(Cols_nulls_50.index, axis=1, inplace=True)
loan_data1.shape

(39717, 54)

In [100]:
loan_data1.agg(['count','size','nunique'])

         id     member_id  loan_amnt  funded_amnt  funded_amnt_inv  term   int_rate  installment  grade  sub_grade  emp_title  emp_length  home_ownership  annual_inc  verification_status  issue_d  loan_status  pymnt_plan  url    desc   purpose  title  zip_code  addr_state  dti    delinq_2yrs  earliest_cr_line  inq_last_6mths  open_acc  pub_rec  revol_bal  revol_util  total_acc  initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee  last_pymnt_d  last_pymnt_amnt  last_credit_pull_d  collections_12_mths_ex_med  policy_code  application_type  acc_now_delinq  chargeoff_within_12_mths  delinq_amnt  pub_rec_bankruptcies  tax_liens
count    39717  39717      39717      39717        39717            39717  39717     39717        39717  39717      37258      38642       39717           39717       39717                39717    39717        39717       39717  26777  39717    39706  39717     39717       39717  39717        39717             39717           39717     39717    39717      39667       39717      39717                39717      39717          39717        39717            39717            39717          39717               39717       39717                    39646         39717            39715               39661                       39717        39717             39717           39661                     39717        39020                 39678
size     39717  39717      39717      39717        39717            39717  39717     39717        39717  39717      39717      39717       39717           39717       39717                39717    39717        39717       39717  39717  39717    39717  39717     39717       39717  39717        39717             39717           39717     39717    39717      39717       39717      39717                39717      39717          39717        39717            39717            39717          39717               39717       39717                    39717         39717            39717               39717                       39717        39717             39717           39717                     39717        39717                 39717
nunique  39717  39717        885       1041         8205                2    371     15383            7     35      28820         11           5            5318           3                   55        3            1       39717  26527     14    19615    823        50        2868     11          526                 9              40         5    21711       1089          82          1                 1137       1138          37850        37518             7976            35148           1356                4040        2616                      101         34930              106                   1                           1            1                 1               1                         1            3                     1

In [101]:
loan_data1.index

RangeIndex(start=0, stop=39717, step=1)

In [102]:
# id is considered as index instead of member_id, because if the same member is applying for a new loan, then member_id might be same but id will be a new id given for that member
## Setting up index is useful for faster runtime, slicing and manipulation
# id column is unique for all rows
loan_data1.set_index('id', inplace=True)

In [103]:
loan_data1.index

Int64Index([1077501, 1077430, 1077175, 1076863, 1075358, 1075269, 1069639, 1072053, 1071795, 1071570,
            ...
              92666,   92552,   92533,   92507,   92402,   92187,   90665,   90395,   90376,   87023], dtype='int64', name='id', length=39717)

In [106]:
loan_data1.iloc[:,:10]

         member_id  loan_amnt  funded_amnt  funded_amnt_inv term        int_rate  installment grade sub_grade emp_title
id
1077501  1296599     5000       5000         4975.0           36 months  10.65%   162.87       B     B2                               NaN
1077430  1314167     2500       2500         2500.0           60 months  15.27%    59.83       C     C4                             Ryder
1077175  1313524     2400       2400         2400.0           36 months  15.96%    84.33       C     C5                               NaN
1076863  1277178    10000      10000        10000.0           36 months  13.49%   339.31       C     C1               AIR RESOURCES BOARD
1075358  1311748     3000       3000         3000.0           60 months  12.69%    67.79       B     B5          University Medical Group
...            ...        ...          ...              ...         ...      ...          ...   ...       ...                         ...
92187      92174     2500       2500         1075.0           36 months   8.07%    78.42       A     A4                   FiSite Research
90665      90607     8500       8500          875.0           36 months  10.28%   275.38       C     C1        Squarewave Solutions, Ltd.
90395      90390     5000       5000         1325.0           36 months   8.07%   156.84       A     A4                               NaN
90376      89243     5000       5000          650.0           36 months   7.43%   155.38       A     A2                               NaN
87023      86999     7500       7500          800.0           36 months  13.75%   255.43       E     E2                  Evergreen Center

[39717 rows x 10 columns]

In [125]:
#print('Before removing 50% ' , Cols_nulls)
Cols_nulls=get_null_value(loan_data1) 
print('After removing 50%\n', Cols_nulls)
loan_data1.to_csv('loan_data1.csv')

After removing 50%
 member_id                      0.00
loan_amnt                      0.00
funded_amnt                    0.00
funded_amnt_inv                0.00
term                           0.00
int_rate                       0.00
installment                    0.00
grade                          0.00
sub_grade                      0.00
emp_title                      6.19
emp_length                     2.71
home_ownership                 0.00
annual_inc                     0.00
verification_status            0.00
issue_d                        0.00
loan_status                    0.00
pymnt_plan                     0.00
url                            0.00
desc                          32.58
purpose                        0.00
title                          0.03
zip_code                       0.00
addr_state                     0.00
dti                            0.00
delinq_2yrs                    0.00
earliest_cr_line               0.00
inq_last_6mths                 0.00
open_acc                       0.00
pub_rec                        0.00
revol_bal                      0.00
revol_util                     0.13
total_acc                      0.00
initial_list_status            0.00
out_prncp                      0.00
out_prncp_inv                  0.00
total_pymnt                    0.00
total_pymnt_inv                0.00
total_rec_prncp                0.00
total_rec_int                  0.00
total_rec_late_fee             0.00
recoveries                     0.00
collection_recovery_fee        0.00
last_pymnt_d                   0.18
last_pymnt_amnt                0.00
last_credit_pull_d             0.01
collections_12_mths_ex_med     0.14
policy_code                    0.00
application_type               0.00
acc_now_delinq                 0.00
chargeoff_within_12_mths       0.14
delinq_amnt                    0.00
pub_rec_bankruptcies           1.75
tax_liens                      0.10
dtype: float64

In [111]:
##Rest of the nulls in columns are very less and hence we can impute values to fix it
loan_data1['emp_length'].describe()

count         38642
unique           11
top       10+ years
freq           8879
Name: emp_length, dtype: object

In [112]:
loan_data1['emp_length'].info()

<class 'pandas.core.series.Series'>
Int64Index: 39717 entries, 1077501 to 87023
Series name: emp_length
Non-Null Count  Dtype
--------------  -----
38642 non-null  object
dtypes: object(1)
memory usage: 620.6+ KB

In [121]:
##emp_length is having < and + symbol
loan_data1['emp_length'].replace('+','')

id
1077501    10+ years
1077430     < 1 year
1077175    10+ years
1076863    10+ years
1075358       1 year
             ...
92187        4 years
90665        3 years
90395       < 1 year
90376       < 1 year
87023       < 1 year
Name: emp_length, Length: 39717, dtype: object

In [118]:
loan_data1.describe()

       member_id  loan_amnt  funded_amnt  funded_amnt_inv  installment  annual_inc  dti       delinq_2yrs  inq_last_6mths  open_acc  pub_rec   revol_bal  total_acc  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee  last_pymnt_amnt  collections_12_mths_ex_med  policy_code  acc_now_delinq  chargeoff_within_12_mths  delinq_amnt  pub_rec_bankruptcies  tax_liens
count  3.97e+04   39717.00   39717.00     39717.00         39717.00     3.97e+04    39717.00  39717.00     39717.00        39717.00  39717.00   39717.00  39717.00   39717.00   39717.00       39717.00     39717.00         39717.00         39717.00       39717.00            39717.00    39717.00                 39717.00         39661.0                     39717.0      39717.0         39661.0                   39717.0      39020.00              39678.0
mean   8.50e+05   11219.44   10947.71     10397.45           324.56     6.90e+04       13.32      0.15         0.87            9.29      0.06   13382.53     22.09      51.23      50.99       12153.60     11567.15          9793.35          2263.66           1.36               95.22       12.41                  2678.83             0.0                         1.0          0.0             0.0                       0.0          0.04                  0.0
std    2.66e+05    7456.67    7187.24      7128.45           208.87     6.38e+04        6.68      0.49         1.07            4.40      0.24   15885.02     11.40     375.17     373.82        9042.04      8942.67          7065.52          2608.11           7.29              688.74      148.67                  4447.14             0.0                         0.0          0.0             0.0                       0.0          0.20                  0.0
min    7.07e+04     500.00     500.00         0.00            15.69     4.00e+03        0.00      0.00         0.00            2.00      0.00       0.00      2.00       0.00       0.00           0.00         0.00             0.00             0.00           0.00                0.00        0.00                     0.00             0.0                         1.0          0.0             0.0                       0.0          0.00                  0.0
25%    6.67e+05    5500.00    5400.00      5000.00           167.02     4.04e+04        8.17      0.00         0.00            6.00      0.00    3703.00     13.00       0.00       0.00        5576.93      5112.31          4600.00           662.18           0.00                0.00        0.00                   218.68             0.0                         1.0          0.0             0.0                       0.0          0.00                  0.0
50%    8.51e+05   10000.00    9600.00      8975.00           280.22     5.90e+04       13.40      0.00         1.00            9.00      0.00    8850.00     20.00       0.00       0.00        9899.64      9287.15          8000.00          1348.91           0.00                0.00        0.00                   546.14             0.0                         1.0          0.0             0.0                       0.0          0.00                  0.0
75%    1.05e+06   15000.00   15000.00     14400.00           430.78     8.23e+04       18.60      0.00         1.00           12.00      0.00   17058.00     29.00       0.00       0.00       16534.43     15798.81         13653.26          2833.40           0.00                0.00        0.00                  3293.16             0.0                         1.0          0.0             0.0                       0.0          0.00                  0.0
max    1.31e+06   35000.00   35000.00     35000.00          1305.19     6.00e+06       29.99     11.00         8.00           44.00      4.00  149588.00     90.00    6311.47    6307.37       58563.68     58563.68         35000.02         23563.68         180.20            29623.35     7002.19                 36115.20             0.0                         1.0          0.0             0.0                       0.0          2.00                  0.0

In [122]:
loan_data1.shape

(39717, 53)

In [124]:
loan_data1.head(10)

         member_id  loan_amnt  funded_amnt  funded_amnt_inv term        int_rate  installment grade sub_grade emp_title                  emp_length home_ownership  annual_inc verification_status issue_d loan_status  pymnt_plan url                                                desc                                               purpose             title                                  zip_code addr_state  dti    delinq_2yrs earliest_cr_line  inq_last_6mths  open_acc  pub_rec  revol_bal revol_util  total_acc initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee last_pymnt_d  last_pymnt_amnt last_credit_pull_d  collections_12_mths_ex_med  policy_code application_type  acc_now_delinq  chargeoff_within_12_mths  delinq_amnt  pub_rec_bankruptcies  tax_liens
id
1077501  1296599     5000       5000         4975.0           36 months  10.65%   162.87       B     B2                              NaN  10+ years  RENT           24000.0            Verified     Dec-11   Fully Paid  n          https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/22/11 > I need to upgra...         credit_card                               Computer  860xx    AZ         27.65  0            Jan-85           1                3        0        13648      83.70%      9         f                     0.00       0.00          5863.16      5833.84          5000.00          863.16         0.00                 0.00      0.00                     Jan-15        171.62          May-16             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1077430  1314167     2500       2500         2500.0           60 months  15.27%    59.83       C     C4                            Ryder   < 1 year  RENT           30000.0     Source Verified     Dec-11  Charged Off  n          https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/22/11 > I plan to use t...                 car                                   bike  309xx    GA          1.00  0            Apr-99           5                3        0         1687       9.40%      4         f                     0.00       0.00          1008.71      1008.71           456.46          435.17         0.00               117.08      1.11                     Apr-13        119.66          Sep-13             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1077175  1313524     2400       2400         2400.0           36 months  15.96%    84.33       C     C5                              NaN  10+ years  RENT           12252.0        Not Verified     Dec-11   Fully Paid  n          https://lendingclub.com/browse/loanDetail.acti...                                                NaN      small_business                   real estate business  606xx    IL          8.72  0            Nov-01           2                2        0         2956      98.50%     10         f                     0.00       0.00          3005.67      3005.67          2400.00          605.67         0.00                 0.00      0.00                     Jun-14        649.91          May-16             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1076863  1277178    10000      10000        10000.0           36 months  13.49%   339.31       C     C1              AIR RESOURCES BOARD  10+ years  RENT           49200.0     Source Verified     Dec-11   Fully Paid  n          https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/21/11 > to pay for prop...               other                               personel  917xx    CA         20.00  0            Feb-96           1               10        0         5598         21%     37         f                     0.00       0.00         12231.89     12231.89         10000.00         2214.92        16.97                 0.00      0.00                     Jan-15        357.48          Apr-16             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1075358  1311748     3000       3000         3000.0           60 months  12.69%    67.79       B     B5         University Medical Group     1 year  RENT           80000.0     Source Verified     Dec-11      Current  n          https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/21/11 > I plan on combi...               other                               Personal  972xx    OR         17.94  0            Jan-96           0               15        0        27783      53.90%     38         f                   524.06     524.06          3513.33      3513.33          2475.94         1037.39         0.00                 0.00      0.00                     May-16         67.79          May-16             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1075269  1311441     5000       5000         5000.0           36 months   7.90%   156.46       A     A4             Veolia Transportaton    3 years  RENT           36000.0     Source Verified     Dec-11   Fully Paid  n          https://lendingclub.com/browse/loanDetail.acti...                                                NaN             wedding  My wedding loan I promise to pay back  852xx    AZ         11.20  0            Nov-04           3                9        0         7963      28.30%     12         f                     0.00       0.00          5632.21      5632.21          5000.00          632.21         0.00                 0.00      0.00                     Jan-15        161.03          Jan-16             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1069639  1304742     7000       7000         7000.0           60 months  15.96%   170.08       C     C5        Southern Star Photography    8 years  RENT           47004.0        Not Verified     Dec-11   Fully Paid  n          https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/18/11 > I am planning o...  debt_consolidation                                   Loan  280xx    NC         23.51  0            Jul-05           1                7        0        17726      85.60%     11         f                     0.00       0.00         10110.84     10110.84          6985.61         3125.23         0.00                 0.00      0.00                     May-16       1313.76          May-16             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1072053  1288686     3000       3000         3000.0           36 months  18.64%   109.43       E     E1                  MKC Accounting     9 years  RENT           48000.0     Source Verified     Dec-11   Fully Paid  n          https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/16/11 > Downpayment for...                 car                        Car Downpayment  900xx    CA          5.35  0            Jan-07           2                4        0         8221      87.50%      4         f                     0.00       0.00          3939.14      3939.14          3000.00          939.14         0.00                 0.00      0.00                     Jan-15        111.34          Dec-14             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1071795  1306957     5600       5600         5600.0           60 months  21.28%   152.39       F     F2                              NaN    4 years   OWN           40000.0     Source Verified     Dec-11  Charged Off  n          https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/21/11 > I own a small h...      small_business   Expand Business & Buy Debt Portfolio  958xx    CA          5.55  0            Apr-04           2               11        0         5210      32.60%     13         f                     0.00       0.00           646.02       646.02           162.02          294.94         0.00               189.06      2.09                     Apr-12        152.39          Aug-12             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0
1071570  1306721     5375       5375         5350.0           60 months  12.69%   121.45       B     B5                        Starbucks   < 1 year  RENT           15000.0            Verified     Dec-11  Charged Off  n          https://lendingclub.com/browse/loanDetail.acti...    Borrower added on 12/16/11 > I'm trying to b...               other            Building my credit history.  774xx    TX         18.08  0            Sep-04           0                2        0         9279      36.50%      3         f                     0.00       0.00          1476.19      1469.34           673.48          533.42         0.00               269.29      2.52                     Nov-12        121.45          Mar-13             0.0                         1            INDIVIDUAL       0               0.0                       0            0.0                   0.0

In [126]:
##url and desc don't add much value to the analysis and hence dropped
loan_data1.drop(['url','desc'], axis=1, inplace=True)

In [129]:
loan_data1.shape
print('After removing 50%\n', Cols_nulls)

After removing 50%
 member_id                      0.00
loan_amnt                      0.00
funded_amnt                    0.00
funded_amnt_inv                0.00
term                           0.00
int_rate                       0.00
installment                    0.00
grade                          0.00
sub_grade                      0.00
emp_title                      6.19
emp_length                     2.71
home_ownership                 0.00
annual_inc                     0.00
verification_status            0.00
issue_d                        0.00
loan_status                    0.00
pymnt_plan                     0.00
url                            0.00
desc                          32.58
purpose                        0.00
title                          0.03
zip_code                       0.00
addr_state                     0.00
dti                            0.00
delinq_2yrs                    0.00
earliest_cr_line               0.00
inq_last_6mths                 0.00
open_acc                       0.00
pub_rec                        0.00
revol_bal                      0.00
revol_util                     0.13
total_acc                      0.00
initial_list_status            0.00
out_prncp                      0.00
out_prncp_inv                  0.00
total_pymnt                    0.00
total_pymnt_inv                0.00
total_rec_prncp                0.00
total_rec_int                  0.00
total_rec_late_fee             0.00
recoveries                     0.00
collection_recovery_fee        0.00
last_pymnt_d                   0.18
last_pymnt_amnt                0.00
last_credit_pull_d             0.01
collections_12_mths_ex_med     0.14
policy_code                    0.00
application_type               0.00
acc_now_delinq                 0.00
chargeoff_within_12_mths       0.14
delinq_amnt                    0.00
pub_rec_bankruptcies           1.75
tax_liens                      0.10
dtype: float64